yang_dir: '"asdad"'
deviation_source_file: '""'
openconfig_pkg: '""'
platform_annotation_file: '""'
plugin_dir: '""'
dut: '""'
port: ''
username: '""'
password: '"b"'
test_release: '"dsdfsdfsd"'
test_platform: '""'
